# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10_5jYzcb4SHMzGe1zALOvxO_K61IZhaw
"""

import pandas as pd

column_names = ['Class Name','Left-Weight','Left-Distance','Right-Weight','Right-Distance']

df=pd.read_csv("/content/balance-scale.data", names =column_names)

df

df.value_counts()

df.values

for i in df:
  print(df[i].unique())

df.dtypes

df.describe()

df['total_distance']=df.loc[:,['Left-Distance','Right-Distance']].sum(axis=1)

df

df.drop(['total_distance'],axis=1)

df['Total']=df.iloc[:,3:-1].sum(axis=1)

df

x=df.loc[:,['Left-Weight','Right-Distance']]

df

y=df.iloc[:,-1]

df

df.isnull().sum()